spring.application.name=shared-notepad

jwt.secret-key=${JWT_SECRET_KEY:default-secret-key-for-local-development-make-it-long}
jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=1209600000